export const selectCertificateManagementState = (state) => state.certificateManagement
export const selectCertificateStatusFilter = (state) => state.certificateManagement.statusFilter
export const selectCertificateManagementPage = (state) => state.certificateManagement.page
export const selectCertificateManagementLimit = (state) => state.certificateManagement.limit
export const selectCertificates = (state) => state.certificateManagement.certificates
export const selectEligibleHotels = (state) => state.certificateManagement.eligibleHotels
export const selectCertificatesStatus = (state) => state.certificateManagement.certificatesStatus
export const selectEligibleHotelsStatus = (state) => state.certificateManagement.eligibleHotelsStatus
export const selectIssuanceHubSummary = (state) => state.certificateManagement.issuanceHubSummary
export const selectIssuanceHubHotels = (state) => state.certificateManagement.issuanceHubHotels
export const selectIssuanceHubStatus = (state) => state.certificateManagement.issuanceHubStatus
export const selectIssuanceHubError = (state) => state.certificateManagement.issuanceHubError
export const selectCertificateManagementError = (state) => state.certificateManagement.error
export const selectCertificateOverviewStats = (state) => state.certificateManagement.overviewStats
export const selectCertificateOverviewStatsStatus = (state) => state.certificateManagement.overviewStatsStatus
export const selectCertificateOverviewStatsError = (state) => state.certificateManagement.overviewStatsError
export const selectCertificateOverviewCharts = (state) => state.certificateManagement.overviewCharts
export const selectCertificateOverviewChartsStatus = (state) => state.certificateManagement.overviewChartsStatus
export const selectCertificateOverviewChartsError = (state) => state.certificateManagement.overviewChartsError
export const selectCertificateManagementActionStatus = (state) => state.certificateManagement.actionStatus
export const selectCertificateManagementActionError = (state) => state.certificateManagement.actionError
export const selectCertificateManagementActionSuccess = (state) => state.certificateManagement.actionSuccess
export const selectCertificateDetails = (state) => state.certificateManagement.certificateDetails
export const selectCertificateDetailsStatus = (state) => state.certificateManagement.certificateDetailsStatus
export const selectCertificateDetailsError = (state) => state.certificateManagement.detailsError
export const selectCertificateTimeline = (state) => state.certificateManagement.timeline
export const selectCertificateTimelineStatus = (state) => state.certificateManagement.timelineStatus
export const selectCertificateTimelineError = (state) => state.certificateManagement.timelineError
export const selectCertificateTimelinePage = (state) => state.certificateManagement.timelinePage
export const selectCertificateTimelineHasNext = (state) => state.certificateManagement.timelineHasNext
export const selectCertificateTimelineTotal = (state) => state.certificateManagement.timelineTotal

